---
- name: 'Check if Composer is already installed and if so, register its version'
  shell: "{{ composer_parentdir }}/composer --version"
  ignore_errors: true
  register: composer_installed_version
  changed_when: false

- name: Remove the previous Composer installation
  file:
    path: "{{ composer_parentdir }}/composer"
    state: absent
  when: composer_version not in composer_installed_version.stdout

- name: Download the Composer installer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/usr/local/src/composer-installer.php"
    mode: 0755
  when: composer_installed_version|failed or composer_version not in composer_installed_version.stdout

- name: Execute the Composer installer
  shell: 'php /usr/local/src/composer-installer.php'
  args:
    chdir: /usr/local/src
    creates: composer.phar
  when: composer_installed_version|failed or composer_version not in composer_installed_version.stdout

- name: Move composer.phar to the executable path
  shell: "mv composer.phar {{ composer_parentdir }}/composer"
  args:
    chdir: /usr/local/src
    creates: "{{ composer_parentdir }}/composer"
  when: composer_installed_version|failed or composer_version not in composer_installed_version.stdout
